/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageList: typeof import('./src/components/Upload/Upload/ImageList.vue')['default']
    Item: typeof import('./src/components/VirtualList/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadCompressor: typeof import('./src/components/Upload/UploadCompressor.vue')['default']
    UploadFile: typeof import('./src/components/Upload/UploadFile.vue')['default']
    UploadIcon: typeof import('./src/components/Upload/Upload/UploadIcon.vue')['default']
    UploadImage: typeof import('./src/components/Upload/Upload/UploadImage.vue')['default']
    UploadWrap: typeof import('./src/components/Upload/Upload/UploadWrap.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanSpace: typeof import('vant/es')['Space']
    VanUploader: typeof import('vant/es')['Uploader']
    VirtualItem: typeof import('./src/components/VirtualList/VirtualItem/VirtualItem.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/VirtualList.vue')['default']
  }
}
